(defvar N (read))
(defvar forget (- 2025 N))
(dolist (i '(1 2 3 4 5 6 7 8 9))
  (dolist (j '(1 2 3 4 5 6 7 8 9))
    ;(format t "~d , ~d~%" (* i j) forget)
    (if (= (* i j) forget)
      (format t "~d x ~d~%" i j)
    )
  )
)
